CREATE TABLE PageType (
	PageTypeId UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	ParentPageTypeId UNIQUEIDENTIFIER NULL,
	Name VARCHAR(100) NOT NULL,
	IsFolder BIT NOT NULL,
	ControllerType VARCHAR(200) NULL,
	ActionName VARCHAR(50) NULL,
	ModelType VARCHAR(200) NULL
);

CREATE TABLE Page (
	PageId UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	ParentPageId UNIQUEIDENTIFIER NULL,
	PageTypeId UNIQUEIDENTIFIER NULL,
);

CREATE TABLE PageLanguage (
	PageId UNIQUEIDENTIFIER NOT NULL,
	Language VARCHAR(5) NOT NULL,
	NameUrl VARCHAR(50) NOT NULL,
	CopyFromLanguage VARCHAR(5) NULL,
	ContentJson VARCHAR(MAX) NULL,
	PRIMARY KEY (PageId, Language)
);

ALTER TABLE PageType ADD CONSTRAINT fk_PageType_PageType FOREIGN KEY (ParentPageTypeId) REFERENCES PageType(PageTypeId);
ALTER TABLE Page ADD CONSTRAINT fk_Page_Page FOREIGN KEY (ParentPageId) REFERENCES Page(PageId);
ALTER TABLE Page ADD CONSTRAINT fk_Page_PageType FOREIGN KEY (PageTypeId) REFERENCES PageType(PageTypeId);
ALTER TABLE PageLanguage ADD CONSTRAINT fk_PageLanguage_Page FOREIGN KEY (PageId) REFERENCES Page(PageId);