//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeanLucCMS.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageLanguage
    {
        public System.Guid PageId { get; set; }
        public string Language { get; set; }
        public string NameUrl { get; set; }
        public string CopyFromLanguage { get; set; }
        public string ContentJson { get; set; }
    
        public virtual Page Page { get; set; }
    }
}
